### ISSUE TITLE
AWS Secrets Manager

### ISSUE THREAD

**Issue by techno-pixel** [aws-quickstart/quickstart-uipath-orchestrator#43]
Hi there,

I dont have much experience in AWS, at all, and I am standing up Orchestrator on a government network, therefore I need to implement secrets manager for the orchestrator password in the main.template.yaml file.

Currently I have this in the yaml file for the section containing the orchestrator password: (note the password and ARN values are fake)

OrchestratorPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: uipathtestjadsecretspass
      Description: Orchestrator Password
      SecretString: '{"password":"passwordexample"}'
      ReplicaRegions:
      - Region: ca-central-1
      KmsKeyId: *put ARN:aws:key:blahblah here*
      Tags:
        -
          Key: password
          Value: passwordexample

using this, i receive the error that the parameter "Properties" is invalid, however every documentation I look at has it, and I don't see what the issue is... if i remove it, then the error moves down to Description: and the YAML not being well-formed.

Please if anybody has any advice or knowledge on adding secrets to the template for orchestrator it would be greatly appreciated :)

**Comment by ubikusss** [comment]
Hey, please check and see if this is an indenting issue.

**Comment by techno-pixel** [comment]
![image](https://user-images.githubusercontent.com/55169430/148786461-b0c12b8c-fb6b-4339-8af7-795e198497e3.png)

**Comment by ubikusss** [comment]
If I understand the use case correctly you want to store the secret you use for the orchestrator password in the deployment in a secrets manager secret

Most likely the issue is with `KmsKeyId` which is not properly indented. It's under `ReplicaRegions` :
![image](https://user-images.githubusercontent.com/10058111/148904512-977d9dd3-8191-4774-9584-b86d2056f899.png)

Here are some examples we used in another project we have:

```  
RDSPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Password for the SF RDS instance.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true
  OrgSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Org secret
      SecretString: '{}'
  PlatformSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Password for the SF platform.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true
  ArgoCdSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Password for ArgoCd.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludePunctuation: true
```
